### ISSUE TITLE
RSpec fails to run out of the box

### ISSUE THREAD

**Issue by W0lfbane** [jhu-ep-coursera/fullstack-course1-module3#8]
While attempting to setup this assignment, I initially ran RSpec, before writing any code, after installing the required gems, as I would normally do with any test in place. For some reason the test fails, I cannot figure out why?

This is the console output:

```
C:/Sites/fullstack-course1-module3/Assignments/Lesson03-Assignment01-HTTP-Client/student-start/spec/recipe_spec.rb:1:in `require_relative': C:/Sites/fullstack-course1-module3/Assignments/Lesson03-Assignment01-HTTP-Client/student-start/module3_1_assignment.rb:5: syntax error, unexpected '\n', expecting :: or '[' or '.' (SyntaxError)
C:/Sites/fullstack-course1-module3/Assignments/Lesson03-Assignment01-HTTP-Client/student-start/module3_1_assignment.rb:9: syntax error, unexpected keyword_end, expecting end-of-input
        from C:/Sites/fullstack-course1-module3/Assignments/Lesson03-Assignment01-HTTP-Client/student-start/spec/recipe_spec.rb:1:in `<top (required)>'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from C:/RubyOnRails/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from C:/RubyOnRails/Ruby2.2.0/bin/rspec:23:in `load'
        from C:/RubyOnRails/Ruby2.2.0/bin/rspec:23:in `<main>'
```

**Comment by W0lfbane** [comment]
Miraculously, it seems to have fixed itself on it's own... no clue what the problem was.
